# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaseweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.IntegerField()),
                ('location_site', models.CharField(max_length=6)),
                ('location_suite', models.CharField(max_length=10)),
                ('location_rack', models.CharField(max_length=11)),
                ('location_unit', models.CharField(max_length=11)),
                ('specs_brand', models.CharField(max_length=10)),
                ('specs_chassis', models.TextField()),
                ('specs_hardwareRaidCapable', models.CharField(max_length=4)),
                ('specs_cpu_type', models.CharField(max_length=40)),
                ('specs_cpu_quantity', models.IntegerField()),
                ('specs_ram_size', models.IntegerField()),
                ('specs_ram_unit', models.CharField(max_length=2)),
                ('serialNumber', models.CharField(max_length=32)),
                ('contract_id', models.CharField(max_length=32)),
                ('contract_customerId', models.IntegerField()),
                ('contract_salesOrgId', models.IntegerField()),
                ('contract_deliveryStatus', models.CharField(max_length=16)),
                ('contract_reference', models.CharField(max_length=40)),
                ('contract_internalReference', models.CharField(max_length=16)),
                ('contract_startsAt', models.DateTimeField()),
                ('contract_sla', models.CharField(max_length=40)),
                ('contract_contractTerm', models.IntegerField()),
                ('contract_billingCycle', models.IntegerField()),
                ('contract_billingFrequency', models.CharField(max_length=5)),
                ('contract_pricePerFrequency', models.FloatField()),
                ('contract_currency', models.CharField(max_length=3)),
                ('networkInterfaces', models.TextField()),
            ],
        ),
    ]
